import {abilities,skills,spells,tales,aptitudes} from './data.js';
import {derived,active,clone,d20,validate} from './engine.js';
import {get,commit,undoLast,exportState,parseImport,replace,restorePrevious,rawState} from './storage.js';
import {bindLongPress} from './gestures.js';
import {createResultNotice} from './feedback.js';
const $=q=>document.querySelector(q),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),sign=n=>n>=0?'+'+n:String(n),uid=()=>crypto.randomUUID();
const icons=['pipe','staff','register','bag','rod','lantern','inspiration','spell','concentration','vitality','shield','glide','reaction','tales','healing','illusion','rest','social','journal','combat'];
const img=(name,cls='')=>`<img class="icon ${cls}" src="./icone-${icons.includes(name)?name:'bag'}.png" alt="" width="52" height="52">`;
const btn=(label,action,extra='')=>`<button type="button" data-do="${action}" ${extra}>${label}</button>`;
const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'step="1"':''}></label>`;
const select=(name,label,options,value)=>`<label>${label}<select name="${name}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const check=(name,label,value=false)=>`<label><input name="${name}" type="checkbox" ${value?'checked':''}>${label}</label>`;
let offlineReady=false;
let view='accueil',tab='actions',socialTab='skills',journalTab='notes',mode='normal',search='',filter='',noteId=null,busy=false,modalToken=uid(),dialogCallback=null,noteTimer;
const notice=createResultNotice($('#notice'),document);
function notify(text,kind='spirit'){notice.show(text,kind);if(get().settings.haptics&&navigator.vibrate&&!matchMedia('(prefers-reduced-motion: reduce)').matches)try{navigator.vibrate(kind==='damage'?[30,30,20]:kind==='critical'?[20,20,40]:12)}catch{}}
function error(err){const box=$('#modal-error');if(box){box.textContent=err.message||String(err);box.hidden=false;}else notify(err.message||String(err),'damage');}
function render(){const s=get(),d=derived(s);document.body.dataset.view=view;document.body.classList.toggle('contrast',s.settings.contrast);document.body.classList.toggle('reduce-motion',s.settings.reduceMotion);$('#scenery').style.backgroundImage=`linear-gradient(#07131b45,#07131b88),url('./fond-${view}.webp')`;$('#header').innerHTML=`<span class="brand">WONQ</span><div class="row">${btn('Annuler','undo')}${btn('Réglages','settings')}</div>`;$('#nav').innerHTML=[['accueil','Accueil','register'],['combat','Combat','combat'],['social','Social','social'],['journal','Journal','journal']].map(([id,label,icon])=>btn(`${img(icon)}${label}`,'nav',`data-view="${id}" class="${view===id?'selected':''}" ${view===id?'aria-current="page"':''}`)).join('');$('#app').innerHTML=view==='accueil'?home(s):view==='combat'?combat(s,d):view==='social'?social(s,d):journal(s);}
function home(s){return `<div class="hero"><div><div class="eyebrow">Hadozee · Barde ${s.character.level} · Collège des Esprits</div><h1>${esc(s.character.name)}</h1><p class="subtitle">${esc(s.character.subtitle)}</p></div><div class="home-actions">${[['combat','Combat','Les esprits veillent.','combat'],['social','Social','Rencontres & inventaire','social'],['journal','Journal','Ceux que l’on n’oublie pas','journal']].map(([id,t,sub,icon])=>btn(`${img(icon,'aura')}<span><b>${t}</b><small>${sub}</small></span><span class="fixed" aria-hidden="true">›</span>`,'nav',`data-view="${id}" class="home-button"`)).join('')}<p class="muted">Reprendre · ${s.resources.hp}/${derived(s).hpMax} PV · rencontre ${s.encounter}, tour ${s.turn.number}<br>Sauvegarde sur cet appareil · <span id="offline-state">${offlineReady?'Disponible hors ligne':'Préparation hors ligne…'}</span></p></div></div>`;}
function card(id,title,subtitle,icon,action,detail=''){return `<div class="action-card">${btn(`${img(icon)}<strong>${esc(title)}</strong><small>${esc(subtitle)}</small>`,action,`data-id="${esc(id)}" data-detail="${esc(detail||action+':'+id)}"`)}${btn('Détails','detail',`data-id="${esc(detail||action+':'+id)}" class="detail" aria-label="Détails : ${esc(title)}"`)}</div>`;}
function combat(s,d){const r=s.resources;return `<div class="status">${btn(`<b>${r.hp} <small>/ ${d.hpMax}</small></b><small>PV · ${r.temp} temporaires</small>`,'health')}${btn(`<b>${d.ac}</b><small>Armure</small>`,'armor')}${btn(`<b>${r.inspiration}/${s.character.inspiration}</b><small>Inspirations</small>`,'ability','data-id="inspire"')}</div><div class="row" style="margin-top:16px"><div><div class="eyebrow">Rencontre ${s.encounter}</div><h2>Tour ${s.turn.number}</h2></div>${btn(s.turn.active?'Terminer le tour':'Commencer mon tour','turn','class="fixed"')}</div><div class="economy">${[['action','Action'],['bonus','Bonus'],['reaction','Réaction']].map(([k,t])=>`<span class="${s.turn[k]?'spent':''}">${t}<br>${s.turn[k]?'utilisée':'disponible'}</span>`).join('')}</div><div class="row">${btn(`Déplacement ${s.turn.move}/${d.speed+s.turn.extraMove} m`,'move')}${btn('Annuler ce tour','cancelTurn')}</div><div class="toolbar" aria-label="Modes de jet">${[['normal','Normal'],['adv','Avantage'],['dis','Désavantage']].map(([v,t])=>btn(t,'mode',`data-id="${v}" class="${mode===v?'selected':''}" aria-pressed="${mode===v}"`)).join('')}</div>${s.resources.hp===0?`<section class="panel"><h3>${s.death.dead?'Wonq est mort':s.death.stable?'Stabilisé à 0 PV':'Wonq est à terre'}</h3><p>${s.death.success} réussites · ${s.death.fail} échecs</p><div class="row">${btn('Jet de mort','death')}${btn('Stabiliser (MJ)','stabilize')}</div></section>`:''}${s.concentration?`<div class="effect">${img('concentration')}<strong>${esc(s.concentration.name)}</strong><p>${s.concentrationDue?`JS CON DD ${s.concentrationDue} à résoudre`:'Concentration active'}</p><div class="row">${s.concentrationDue?btn('Sauvegarde','concSave'):''}${btn('Interrompre','concStop')}</div></div>`:''}<div class="toolbar">${[['actions','Actions'],['spells','Sorts'],['spirits','Esprits'],['status','Suivi']].map(([v,t])=>btn(t,'tab',`data-id="${v}" class="${tab===v?'selected':''}"`)).join('')}</div>${tab==='actions'?actions(s,d):tab==='spells'?spellList(s):tab==='spirits'?spirits(s):tracking(s,d)}`;}
function actions(s,d){return `<section class="panel"><div class="resource-title"><span>Inspiration d8</span><b>${s.resources.inspiration}/${s.character.inspiration}</b></div><div class="tokens" aria-label="${s.resources.inspiration} inspirations restantes">${Array.from({length:s.character.inspiration},(_,i)=>img('inspiration',i<s.resources.inspiration?'aura':'spent')).join('')}</div><div class="grid">${card('mockery','Moquerie cruelle','Action · SAG DD '+d.dc,'tales','spell')}${card('word','Mot de guérison','Bonus · soin à 18 m','healing','spell')}${card('draw','Préparer un Conte','Bonus · 1 inspiration','tales','ability')}${card('inspire','Inspirer un allié','Bonus · 1 inspiration','inspiration','ability')}${card('staff1','Bâton, une main',sign(d.staffAttack)+' · 1d6'+sign(d.staffMod),'staff','attack')}${card('staff2','Bâton, deux mains',sign(d.staffAttack)+' · 1d8'+sign(d.staffMod),'staff','attack')}${card('dagger','Dague',sign(d.prof+d.mods[1])+' · 1d4'+sign(d.mods[1]),'combat','attack')}${card('dodge','Esquive Hadozee',s.resources.dodge+'/3 · réaction','shield','ability')}${card('glide','Planeur','Réaction · chute ≥3 m','glide','ability')}${card('misty','Foulée brumeuse',s.resources.misty?'Bonus · gratuite disponible':'Bonus · emplacement N2','glide','spell')}</div></section><section class="panel"><h3>Actions & objets</h3><div class="grid">${Object.entries(aptitudes).filter(([id])=>!['draw','inspire','dodge','glide','double','cortege','commandSmoke','eyes'].includes(id)).map(([id,a])=>card(id,a[0],{action:'Action',bonus:'Action bonus',reaction:'Réaction'}[a[1]],a[2],'ability')).join('')}${card('staff1','Attaque d’opportunité','Réaction · déclencheur à confirmer','reaction','opportunity','attack:staff1')}</div></section>`;}
function spellList(s){return `<section class="panel"><h3>Emplacements</h3><div class="grid">${s.resources.slots.map((n,i)=>`<div><div class="resource-title"><span>Niveau ${i+1}</span><b>${n}/${s.character.slots[i]}</b></div><div class="tokens">${Array.from({length:s.character.slots[i]},(_,j)=>img('spell',j<n?'aura':'spent')).join('')}</div></div>`).join('')}</div><p class="muted">DD ${derived(s).dc} · attaque ${sign(derived(s).attack)} · ${active(s,'pipe')&&s.character.focusHouse?'focaliseur +1d6 actif':'bonus de focaliseur inactif'}</p></section>${[0,1,2,3,4].map(l=>`<section class="panel"><h3>${l?'Niveau '+l:'Tours de magie'}</h3><div class="grid">${spells.filter(x=>x.level===l&&!x.item).map(sp=>card(sp.id,sp.name,`${sp.cost==='bonus'?'Bonus':'Action'} · ${sp.range}`,sp.icon,'spell')).join('')}</div></section>`).join('')}<section class="panel"><h3>Le bâton · ${s.resources.staff}/3 charges</h3><div class="grid">${spells.filter(x=>x.item).map(sp=>card(sp.id,sp.name,sp.charge+' charge(s) · '+sp.cost,sp.icon,'spell')).join('')}</div></section><section class="panel"><h3>Séance de spiritisme</h3><p>${s.session?esc(s.session.name)+' · N'+s.session.level:'Aucun sort temporaire'}</p>${btn('Préparer une séance','session')}${s.session?btn('Lancer le sort de séance','sessionCast'):''}</section>`;}
function spirits(s){return `<section class="panel"><div class="eyebrow">Contes · ${s.character.profile==='app'?'Application actuelle (UA)':'Dossier fourni'}</div><h3>${s.tale?esc(tales[s.tale-1][0]):s.choices?'Deux voix attendent votre choix':'La fumée attend'}</h3>${s.tale?`<p>${esc(tales[s.tale-1][s.character.profile==='app'?1:2])}</p>${btn('Offrir ce Conte','offer')}`:''}${s.choices?`<div class="row">${s.choices.map(n=>btn(n+' · '+esc(tales[n-1][0]),'choose',`data-id="${n}"`)).join('')}</div>`:''}<div class="grid">${card('draw','Préparer','1 inspiration · bonus','tales','ability')}${card('double','Deux voix',s.resources.voice+'/1 · repos long','pipe','ability')}</div></section><section class="panel"><h3>La Longue Mémoire · ${s.resources.pipe}/5</h3><div class="grid">${['cortege','commandSmoke','eyes'].map(id=>card(id,aptitudes[id][0],aptitudes[id][1],aptitudes[id][2],'ability')).join('')}</div><p>${s.cortege.length} silhouette(s) · CA 15 · 1 PV · 9 m</p><p class="muted">Retirez une silhouette détruite dans le suivi MJ.</p></section><section class="panel"><h3>Les huit voix</h3>${tales.map((t,i)=>`<details><summary>${i+1} · ${esc(t[0])}</summary><p>${esc(t[s.character.profile==='app'?1:2])}</p></details>`).join('')}</section>${effects(s)}`;}
function effects(s){return `<section class="panel"><h3>Effets & bénéficiaires</h3>${s.effects.length?s.effects.map(e=>`<div class="effect"><strong>${esc(e.target)}</strong><p>${esc(e.label)}</p><small>${e.expiry==='targetEnd'?'Échéance : fin du prochain tour de cette cible (confirmer au bon moment)':e.expiry==='manual'?'Durée à suivre avec le MJ':e.expiry==='concentration'?'Lié à la concentration':`${e.expiry==='start'?'Début':'Fin'} du tour ${e.at} de Wonq`}</small><div class="row">${['tale1','tale5','tale8'].includes(e.id)?btn('Déclencher le d8','trigger',`data-id="${e.uid}"`):''}${btn('Terminer','effectRemove',`data-id="${e.uid}"`)}</div></div>`).join(''):'<p class="muted">Aucun effet suivi.</p>'}</section>`;}
function tracking(s,d){return `<section class="panel"><h3>Sauvegardes</h3><div class="grid three">${abilities.map((a,i)=>btn(`${a} ${sign(d.saves[i])}`,'save',`data-id="${i}"`)).join('')}</div><p class="muted">Les 1 et 20 naturels n’imposent pas un échec ou une réussite automatique.</p></section><section class="panel"><h3>États</h3><div class="toolbar">${['À terre','Charmé','Effrayé','Aveuglé','Assourdi','Empoisonné','Entravé','Agrippé','Neutralisé','Étourdi','Paralysé','Inconscient','Silence'].map(c=>btn(c,'condition',`data-id="${c}" class="${s.conditions.includes(c)?'selected':''}"`)).join('')}</div></section>${effects(s)}<section class="panel"><h3>Repos & rencontre</h3><div class="grid">${btn('Repos court','rest','data-id="short"')}${btn('Repos long','rest','data-id="long"')}${btn('Passage de l’aube','rest','data-id="dawn"')}${btn('Réinitialiser la rencontre','encounter','class="danger"')}</div></section><section class="panel"><h3>Arbitrage du MJ</h3>${s.resources.aid?btn('Terminer Aide (+ '+s.resources.aid+' PV)','aidEnd'):''}${btn('Jet libre du MJ','freeRoll')}<p class="muted">Compteurs, emplacements, silhouettes et échéances peuvent être corrigés explicitement.</p>${btn('Ajuster les ressources','adjust')}${btn('Modifier les effets / silhouettes','editEffects')}${btn('Historique des opérations','history')}</section>`;}
function social(s,d){return `<div class="eyebrow">Une halte sur le chemin</div><h2>Rencontres & souvenirs</h2><div class="toolbar">${[['skills','Compétences'],['inventory','Inventaire'],['register','Absents']].map(([id,t])=>btn(t,'socialTab',`data-id="${id}" class="${socialTab===id?'selected':''}"`)).join('')}</div>${socialTab==='skills'?`<section class="panel"><div class="toolbar">${[['normal','Normal'],['adv','Avantage'],['dis','Désavantage']].map(([id,t])=>btn(t,'mode',`data-id="${id}" class="${mode===id?'selected':''}"`)).join('')}</div><div class="grid">${skills.map(([name,a],i)=>btn(`<span>${name}<small>${abilities[a]} · ${s.character.skillRanks[i]===2?'Expertise':s.character.skillRanks[i]===1?'Maîtrise':'Touche-à-tout'}</small></span><b>${sign(d.skills[i])}</b>`,'skill',`data-id="${i}" class="skill"`)).join('')}</div></section><section class="panel"><h3>Caractéristiques</h3><div class="grid three">${abilities.map((a,i)=>btn(`${a} ${sign(d.mods[i]+Math.floor(d.prof/2))}`,'check',`data-id="${i}"`)).join('')}</div><p class="muted">Touche-à-tout inclus aux tests non maîtrisés.</p>${btn('Initiative '+sign(d.initiative),'initiative')}<h3>Langues & instruments</h3><p>${esc(s.character.languages)}</p><p>${esc(s.character.tools)}</p>${btn('Test d’instrument','toolRoll')}<p class="muted">Perception passive ${10+d.skills[12]} · Intuition ${10+d.skills[10]} · Investigation ${10+d.skills[6]}</p></section>`:socialTab==='inventory'?inventory(s):register(s)}`;}
function inventory(s){return `<section class="panel"><div class="row"><h3>Les affaires de Wonq</h3>${btn('Ajouter','newItem','class="fixed"')}</div><label class="sr-only" for="search">Rechercher un objet</label><input id="search" type="search" placeholder="Rechercher un objet…" value="${esc(search)}"><div class="toolbar">${[['','Tout'],['magic','Magique'],['equipped','Équipé']].map(([id,t])=>btn(t,'filter',`data-id="${id}" class="${filter===id?'selected':''}"`)).join('')}</div><p class="muted">${s.items.filter(i=>i.attuned&&i.qty>0).length}/3 harmonisations · ${s.coins} po ${btn('Monnaie','coins')}</p><div class="grid inventory">${s.items.filter(i=>(i.name+' '+i.description).toLowerCase().includes(search.toLowerCase())&&(!filter||filter==='magic'&&i.rarity!=='Ordinaire'||filter==='equipped'&&i.equipped&&i.qty)).map(i=>btn(`${img(i.icon,i.rarity!=='Ordinaire'?'magic':'')}<b>${esc(i.name)}</b><small>${esc(i.rarity)} · ×${i.qty}<br>${i.attuned?'Harmonisé':i.equipped?'Équipé':esc(i.container)}</small>`,'item',`data-id="${esc(i.id)}" data-detail="item:${esc(i.id)}" class="item-tile"`)).join('')}</div></section>`;}
function register(s){return `<section class="panel"><h3>Le Registre des Absents</h3><p>${s.registerEntries.filter(x=>x.status==='À retrouver').length}/30 absents · ${s.resources.register}/1 recherche quotidienne</p><div class="row">${btn('Ajouter un nom','registerNew')}${btn('Où es-tu ?','registerUse')}</div>${s.registerEntries.map(x=>btn(`<strong>${esc(x.name)}</strong><small>${esc(x.status)} · ${esc(x.description)}</small>`,'registerEdit',`data-id="${x.id}" class="note"`)).join('')}<p class="muted">Un silence ne prouve jamais un décès.</p></section>`;}
function journal(s){return `<div class="eyebrow">Les traces que l’on garde</div><h2>Journal du voyage</h2><div class="toolbar">${[['notes','Notes'],['history','Jets'],['trash','Corbeille']].map(([id,t])=>btn(t,'journalTab',`data-id="${id}" class="${journalTab===id?'selected':''}"`)).join('')}</div><section class="panel"><input id="search" type="search" aria-label="Rechercher" placeholder="Chercher un nom, un indice…" value="${esc(search)}">${journalTab==='history'?s.log.slice().reverse().filter(l=>l.text.toLowerCase().includes(search.toLowerCase())).map(l=>`<div class="log-entry"><time>${new Date(l.time).toLocaleString('fr-FR')} · rencontre ${l.encounter}, tour ${l.turn}</time>${esc(l.text)}</div>`).join('')||'<p>Aucun jet enregistré.</p>':`<div class="row">${btn('Nouvelle note','newNote')}${btn('Catégories','categories')}${btn('Exporter les notes','exportNotes')}</div><div class="toolbar">${btn('Toutes','noteFilter','data-id=""')}${btn('Favoris','noteFilter','data-id="favorite"')}${s.categories.map(c=>btn(esc(c.name),'noteFilter',`data-id="${esc(c.id)}" style="border-color:${/^#[0-9a-f]{6}$/i.test(c.color)?c.color:'#ccb98e'}"`)).join('')}</div>${s.notes.filter(n=>!!n.deleted===(journalTab==='trash')&&(n.title+' '+n.body+' '+(n.tags||'')).toLowerCase().includes(search.toLowerCase())&&(!filter||filter==='favorite'&&n.favorite||filter===n.category)).sort((a,b)=>(b.favorite-a.favorite)||b.updated.localeCompare(a.updated)).map(n=>btn(`<strong>${n.favorite?'★ ':''}${esc(n.title||'Sans titre')}</strong><small>${esc(s.categories.find(c=>c.id===n.category)?.name||'Sans catégorie')} · ${esc(n.session||new Date(n.updated).toLocaleDateString('fr-FR'))}</small><p>${esc(n.body.slice(0,110))}</p>`,'note',`data-id="${n.id}" class="note"`)).join('')||'<p class="empty">Votre carnet attend son premier souvenir.</p>'}`}</section>`;}
function modal(title,body,submit){notice.hide();if($('#modal').open)$('#modal').close();modalToken=uid();dialogCallback=submit;$('#modal-content').innerHTML=`<div class="dialog-head"><h2 id="modal-title">${esc(title)}</h2>${btn('Fermer','close')}</div><form id="form"><div id="modal-error" class="error" role="alert" hidden></div>${body}${submit?'<button type="submit" class="selected" style="width:100%;margin-top:14px">Confirmer</button>':''}</form>`;$('#modal').showModal();}
function act(e,token=modalToken){if(busy)return;busy=true;try{const old=get().log.length;commit(e,token);$('#modal').close();render();const entry=get().log.at(-1);if(entry&&get().log.length>=old)notify(entry.text,entry.kind);}catch(err){error(err);}finally{busy=false;}}
function confirmAction(title,description,e){modal(title,`<p>${esc(description)}</p>`,()=>act(e));}
function rolls(){return select('mode','Mode de jet',[['normal','Normal'],['adv','Avantage'],['dis','Désavantage']],mode)+field('manual','d20 manuel (facultatif)','','number');}
function rollParams(fd){return {mode:fd.get('mode')||mode,manual:fd.get('manual')!==null&&fd.get('manual')!==''?Number(fd.get('manual')):null};}
function test(label,bonus,extra={}){modal(label,`<p>Bonus ${sign(bonus)} · les dés et le calcul seront affichés.</p>${rolls()}`,fd=>act({type:'roll',label,bonus,...rollParams(fd),...extra}));}
function attack(id,opportunity=false){const d=derived(get()),bonus=id==='dagger'?d.prof+d.mods[1]:d.staffAttack;modal(opportunity?'Attaque d’opportunité':'Attaque · '+(id==='dagger'?'Dague':'Bâton'),`<p>${opportunity?'Réaction : ennemi visible quittant volontairement votre allonge, sans Désengagement.':'Une action, une attaque. Wonq ne possède pas Attaque supplémentaire.'}</p>${rolls()}${id!=='dagger'?check('reach','Allonge de 4,5 m (bâton actif, une fois par tour)'):''}`,fd=>{try{const p=rollParams(fd),r=d20(bonus,p.mode,p.manual),e={type:'attack',weapon:id,opportunity,reach:fd.has('reach'),roll:r};modal('Jet d’attaque',`<div class="big-roll">${r.total}</div><p>${esc(r.text)}</p><p>${r.natural===20?'20 naturel : critique.':r.natural===1?'1 naturel : échec automatique.':'La cible est-elle touchée ? Confirmation du MJ.'}</p><div class="row">${btn('Touché','confirmHit','data-hit="true"')}${btn('Manqué','confirmHit','data-hit="false"')}</div>`,null);pendingAttack=e;}catch(err){error(err)}});}
let pendingAttack=null;
function spell(id){const s=get(),sp=spells.find(x=>x.id===id);modal(sp.name,`${img(sp.icon,'dialog-art aura')}<p>${esc(sp.range)} · ${esc(sp.duration)}</p><p>${esc(sp.description)}</p>${sp.level&&!sp.item?select('level','Emplacement',Array.from({length:5-sp.level},(_,i)=>[sp.level+i,`N${sp.level+i} · ${s.resources.slots[sp.level+i-1]} restant(s)`]),sp.level):''}${sp.free?check('free',`Lancement gratuit (${s.resources[sp.free]}/1)`,!!s.resources[sp.free]):''}${sp.concentration&&s.concentration?`<p class="error">Remplacera la concentration : ${esc(s.concentration.name)}.</p>`:''}${field('target','Cible(s) / bénéficiaire(s)')}${sp.heal||id==='aid'?check('self','Appliquer aussi à Wonq'):''}${sp.save?select('success',`JS ${sp.save} DD ${derived(s).dc} — verdict du MJ`,[['','Choisir le résultat'],['false','Échec'],['true','Réussite']],''):''}${sp.id==='dispel'?field('targetLevel','Niveau du sort à dissiper',4,'number')+rolls():''}`,fd=>{if(sp.save&&fd.get('success')==='')return error(Error('Indiquez le résultat du JS.'));act({type:'spell',id,level:sp.item?sp.level:Number(fd.get('level')||0),free:fd.has('free'),target:fd.get('target'),self:fd.has('self'),success:sp.save?fd.get('success')==='true':undefined,targetLevel:Number(fd.get('targetLevel')||3),...rollParams(fd)});});}
function ability(id){const a=aptitudes[id];if(id==='dodge'){health('dodge');return;}modal(a[0],`${img(a[2],'dialog-art aura')}<p>${esc(a[3])}</p>${id==='inspire'?field('target','Bénéficiaire (autre que Wonq)'):''}${id==='glide'?check('eligible','Chute d’au moins 3 m, espace inoccupé visible, non neutralisé'):''}${id==='cortege'?select('count','Silhouettes',[[1,'Une'],[2,'Deux'],[3,'Trois']],3):''}${id==='commandSmoke'?field('detail','Silhouette et action choisies'):''}`,fd=>act({type:'ability',id,target:fd.get('target'),eligible:fd.has('eligible'),count:Number(fd.get('count')||3),detail:fd.get('detail')}));}
function offer(){const s=get(),n=s.tale;if(!n)return;modal('Offrir un Conte',`<p>${esc(tales[n-1][0])}</p><p>${esc(tales[n-1][s.character.profile==='app'?1:2])}</p>${field('target','Cible visible à 9 m (Wonq pour soi)')}${n===2?rolls():''}${n===7?select('success','JS SAG : résultat du MJ',[['','Choisir'],['false','Échec'],['true','Réussite']],''):''}`,fd=>{const e={type:'offer',target:fd.get('target'),success:fd.get('success')==='true'};if(n===7&&fd.get('success')==='')return error(Error('Indiquez le verdict du MJ.'));if(n===2){try{const p=rollParams(fd),r=d20(derived(s).attack,p.mode,p.manual);pendingAttack={...e,roll:r};modal('Le Duelliste frappe',`<div class="big-roll">${r.total}</div><p>${esc(r.text)}</p><div class="row">${btn('Touché','confirmHit','data-hit="true"')}${btn('Manqué','confirmHit','data-hit="false"')}</div>`,null);}catch(err){error(err)}}else act(e);});}
function health(kind='damage'){let amount='';modal(kind==='dodge'?'Esquive Hadozee & dégâts':'Points de vie',`${kind!=='dodge'?select('kind','Opération',[['damage','Dégâts reçus'],['heal','Soins reçus'],['temp','PV temporaires']],kind):'<p>Entrez les dégâts avant réduction. Réaction et usage seront dépensés ensemble.</p>'}<output id="amount" class="amount">0</output><div class="keypad">${[1,2,3,4,5,6,7,8,9,'C',0,'⌫'].map(n=>btn(n,'digit',`data-id="${n}"`)).join('')}</div>${check('critical','Dégâts d’un critique (important à 0 PV)')}`,fd=>act(kind==='dodge'?{type:'ability',id:'dodge',amount:Number(amount||0),critical:fd.has('critical')}:{type:'hp',kind:fd.get('kind'),amount:Number(amount||0),critical:fd.has('critical')}));$('#modal-content').addEventListener('click',function digit(e){const b=e.target.closest('[data-do=digit]');if(!b)return;const v=b.dataset.id;amount=v==='C'?'':v==='⌫'?amount.slice(0,-1):(amount+v).slice(0,4);$('#amount').textContent=amount||'0';},{signal:modalSignal()});}
let modalAbort;function modalSignal(){modalAbort?.abort();modalAbort=new AbortController();return modalAbort.signal;}
function detail(key){const [type,id]=key.split(':');let title='',description='',icon='register';if(type==='spell'){const sp=spells.find(x=>x.id===id);title=sp.name;description=`${sp.cost} · ${sp.range} · ${sp.duration}\n\n${sp.description}`;icon=sp.icon;}else if(type==='ability'){const a=aptitudes[id];[title,,icon,description]=a;}else if(type==='item'){const i=get().items.find(x=>x.id===id);title=i.name;description=i.description;icon=i.icon;}else{title=id==='dagger'?'Dague':'Bâton du Vagabond Gris';description=id==='dagger'?'Attaque +5, 1d4 +2 perforants. Finesse, légère, lancer 6/18 m.':get().items.find(i=>i.id==='staff')?.description;icon='staff';}modal(title,`${img(icon,'dialog-art aura')}<p class="detail-text">${esc(description)}</p><p class="muted">Résumé opérationnel. Le dossier intégral et les divergences se trouvent dans Réglages → Sources.</p>`,null);}
function itemEdit(id){const existing=get().items.find(i=>i.id===id),i=existing||{id:uid(),name:'Nouvel objet',qty:1,rarity:'Ordinaire',icon:'bag',description:'',notes:'',container:'Sac sans fond',attunement:false,attuned:false,equipped:false};modal(i.name,`${img(i.icon,'dialog-art '+(i.rarity!=='Ordinaire'?'aura':''))}${field('name','Nom',i.name)}<div class="row">${field('qty','Quantité',i.qty,'number')}${field('rarity','Rareté',i.rarity)}</div>${select('icon','Illustration',icons.map(n=>[n,n]),i.icon)}${field('container','Emplacement / conteneur',i.container)}${check('equipped','Équipé',i.equipped)}${check('attunement','Nécessite une harmonisation',i.attunement)}${check('attuned','Harmonisé',i.attuned)}<label>Description complète<textarea name="description">${esc(i.description)}</textarea></label><label>Notes<textarea name="notes">${esc(i.notes)}</textarea></label>${existing?btn('Supprimer cet objet','deleteItem',`data-id="${esc(i.id)}" class="danger"`):''}`,fd=>act({type:'item',item:{...i,name:fd.get('name'),qty:Number(fd.get('qty')),rarity:fd.get('rarity'),icon:fd.get('icon'),container:fd.get('container'),equipped:fd.has('equipped'),attunement:fd.has('attunement'),attuned:fd.has('attuned'),description:fd.get('description'),notes:fd.get('notes')}}));}
function rest(kind){const s=get();modal(kind==='short'?'Repos court':kind==='long'?'Repos long':'Passage de l’aube',`<p>${kind==='short'?'Après au moins une heure : inspirations restaurées, Conte oublié. Dépenser des dés de vie et ajouter le Chant reposant une fois si au moins un dé est dépensé.':kind==='long'?'Après un repos long admissible (2014) : PV, emplacements, inspirations et usages quotidiens restaurés ; jusqu’à quatre dés de vie rendus. Les charges ne récupèrent pas sans aube.':'La pipe récupère 1d4 + 1 charge (maximum 5), le bâton 1d3 (maximum 3). Aucun autre compteur ne change.'}</p>${kind==='short'?select('hd',`Dés de vie à dépenser (${s.resources.hd.filter(Boolean).length}/${s.character.hd} disponibles)`,Array.from({length:s.resources.hd.filter(Boolean).length+1},(_,i)=>[i,i+' dé(s)']),0):''}<p class="muted">La concentration sera arrêtée lors d’un repos court ou long. Opération annulable.</p>`,fd=>act({type:'rest',kind,hd:Number(fd.get('hd')||0)}));}
function noteEdit(id){const n=clone(get().notes.find(x=>x.id===id)||{id:uid(),title:'',body:'',category:get().categories[0]?.id||'',tags:'',favorite:false,session:'',updated:new Date().toISOString(),deleted:false});noteId=n.id;modal(n.deleted?'Note supprimée':'Écrire un souvenir',`${field('title','Titre',n.title)}${select('category','Catégorie',get().categories.map(c=>[c.id,c.name]),n.category)}<label>Note<textarea name="body" class="note-editor" placeholder="Ce que Wonq veut garder…">${esc(n.body)}</textarea></label>${field('tags','Étiquettes (séparées par des virgules)',n.tags)}${field('session','Date de séance (facultative)',n.session,'date')}${check('favorite','Favori',n.favorite)}<p id="note-status" class="muted">Sauvegarde automatique sur cet appareil</p>${btn(n.deleted?'Restaurer':'Supprimer la note','deleteNote',`data-id="${n.id}"`)}${btn('Terminer','close')}`,null);const save=()=>{const fd=new FormData($('#form'));Object.assign(n,{title:fd.get('title'),body:fd.get('body'),category:fd.get('category'),tags:fd.get('tags'),session:fd.get('session'),favorite:fd.has('favorite'),updated:new Date().toISOString()});try{commit({type:'note',note:n});$('#note-status').textContent='Enregistré sur cet appareil';}catch(err){error(err)}};$('#form').addEventListener('input',save);$('#form').addEventListener('change',save);save();}
function categories(){modal('Catégories personnalisées',`<p>Créer, renommer, colorer ou réordonner les catégories. Les notes restent conservées si leur catégorie est supprimée.</p><div id="category-list">${get().categories.map((c,i)=>`<div class="row" data-cat="${c.id}"><input aria-label="Nom de catégorie" name="cat-${c.id}" value="${esc(c.name)}"><input aria-label="Couleur" type="color" name="color-${c.id}" value="${esc(c.color)}" class="fixed" style="width:54px">${btn('↑','catUp',`data-id="${c.id}" class="fixed"`)}${btn('Retirer','catRemove',`data-id="${c.id}" class="fixed"`)}</div>`).join('')}</div>${btn('Nouvelle catégorie','catAdd')}`,fd=>{const list=[...$('#category-list').children].map(row=>({id:row.dataset.cat,name:fd.get('cat-'+row.dataset.cat),color:fd.get('color-'+row.dataset.cat)}));act({type:'categories',categories:list});});}
function settings(){const s=get();modal('Réglages & sauvegardes',`<p class="muted">Version 1.0.0 · Sauvegarde locale, sans synchronisation entre appareils. Exportez régulièrement votre partie.</p><div class="grid">${btn('Exporter la partie','export')}${btn('Importer une partie','import')}${btn('Sauvegarde précédente','previous')}${btn('Sources & arbitrages','sources')}</div>${select('profile','Table des Contes',[['app','Application actuelle · variante UA'],['dossier','Dossier fourni · page 11']],s.character.profile)}<p class="muted">Les effets existants conservent le profil avec lequel ils ont été créés.</p>${check('contrast','Lisibilité renforcée',s.settings.contrast)}${check('reduceMotion','Réduire les animations',s.settings.reduceMotion)}${check('haptics','Vibrations si prises en charge',s.settings.haptics)}<p class="muted">Safari sur iPhone ne fournit généralement pas l’API de vibration. Les effets visuels restent disponibles.</p>${check('focusHouse','Focaliseur +1d6 selon la règle maison du dossier',s.character.focusHouse)}${btn('Éditer les valeurs du personnage','config')}${btn('Exporter les données brutes','raw')}`,fd=>act({type:'config',character:{...s.character,profile:fd.get('profile'),focusHouse:fd.has('focusHouse')},settings:{contrast:fd.has('contrast'),reduceMotion:fd.has('reduceMotion'),haptics:fd.has('haptics')}}));}
function jsonEditor(title,value,onSubmit){modal(title,`<p>Arbitrage explicite du MJ. Les données sont contrôlées avant enregistrement.</p><label>Données JSON<textarea name="json" style="min-height:45svh;font-family:monospace">${esc(JSON.stringify(value,null,2))}</textarea></label>`,fd=>{try{onSubmit(JSON.parse(fd.get('json')))}catch(err){error(err)}});}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function registerEdit(id){const x=get().registerEntries.find(x=>x.id===id)||{id:uid(),name:'',description:'',status:'À retrouver'};modal('Registre des Absents',`${field('name','Nom / désignation',x.name)}${field('description','Description et lien personnel',x.description)}${select('status','Statut',[['À retrouver','À retrouver'],['Revenu','Revenu'],['Décès confirmé','Décès confirmé']],x.status)}`,fd=>act({type:'registerEntry',entry:{...x,name:fd.get('name'),description:fd.get('description'),status:fd.get('status')}}));}
bindLongPress(document,el=>detail(el.dataset.detail));
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close();});
$('#modal').addEventListener('close',()=>{if(!$('#modal').open){pendingAttack=null;modalAbort?.abort();render();}});
document.addEventListener('submit',e=>{if(e.target.id!=='form')return;e.preventDefault();try{dialogCallback?.(new FormData(e.target));}catch(err){error(err)}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const start=e.target.selectionStart;search=e.target.value;render();$('#search').focus();try{$('#search').setSelectionRange(start,start)}catch{}}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-do]');if(!b||b.disabled)return;const id=b.dataset.id,action=b.dataset.do;try{switch(action){
case 'nav':view=b.dataset.view;search='';filter='';render();scrollTo(0,0);break;
case 'mode':mode=id;render();break;
case 'tab':tab=id;render();break;
case 'socialTab':socialTab=id;filter='';search='';render();break;
case 'journalTab':journalTab=id;filter='';search='';render();break;
case 'filter':case 'noteFilter':filter=id;render();break;
case 'close':$('#modal').close();break;
case 'undo':undoLast();render();notify('Dernière opération annulée.');break;
case 'health':health();break;
case 'armor':modal('Armure de Wonq',`<p>CA ${derived(get()).ac} : cuir ${active(get(),'leather')?get().character.armor:10} + DEX ${sign(derived(get()).mods[1])}. Équipement et bonus sont recalculés.</p>`,null);break;
case 'turn':act({type:get().turn.active?'end':'start'},uid());break;
case 'cancelTurn':confirmAction('Annuler le tour en cours','Rétablir les ressources, objets et effets à leur état au début du tour. Les notes personnelles restent conservées. Cette opération peut être annulée.',{type:'cancelTurn'});break;
case 'encounter':confirmAction('Réinitialiser la rencontre','Nouvelle rencontre au tour 1. L’économie du tour est restaurée, les effets de combat et la concentration prennent fin. PV, emplacements, charges et usages par repos sont conservés. Aucun repos n’est accordé.',{type:'encounter'});break;
case 'move':modal('Déplacement',field('amount','Distance à dépenser en mètres',3,'number'),fd=>act({type:'move',amount:Number(fd.get('amount'))}));break;
case 'attack':case 'opportunity':attack(id,action==='opportunity');break;
case 'confirmHit':if(pendingAttack){const p=clone(pendingAttack);act({...p,hit:b.dataset.hit==='true'});}break;
case 'spell':spell(id);break;
case 'ability':ability(id);break;
case 'detail':detail(id);break;
case 'choose':act({type:'choose',number:Number(id)},uid());break;
case 'offer':offer();break;
case 'death':modal('Jet de sauvegarde contre la mort',`<p>10+ : réussite. 1 naturel : deux échecs. 20 naturel : 1 PV. Trois échecs : mort ; trois réussites : stabilisé.</p>${rolls()}`,fd=>act({type:'death',...rollParams(fd)}));break;
case 'aidEnd':confirmAction('Terminer Aide','Les PV actuels et le maximum perdent le bonus d’Aide, au minimum 0 PV.',{type:'aidEnd'});break;
case 'freeRoll':modal('Jet libre du MJ',field('label','Libellé','JS adverse')+field('bonus','Modificateur de la créature (saisi par le MJ)',0,'number')+field('dc','DD facultatif','','number')+rolls(),fd=>act({type:'roll',label:fd.get('label'),bonus:Number(fd.get('bonus')),dc:fd.get('dc')===''?null:Number(fd.get('dc')),...rollParams(fd)}));break;
case 'stabilize':confirmAction('Stabiliser','Confirmer une stabilisation obtenue par intervention ou arbitrage du MJ.',{type:'stabilize'});break;
case 'concSave':modal('Sauvegarde de concentration',rolls(),fd=>act({type:'concentration',...rollParams(fd)}));break;
case 'concStop':confirmAction('Arrêter la concentration','L’effet du sort de concentration prend fin.',{type:'concentration',stop:true});break;
case 'condition':act({type:'condition',name:id},uid());break;
case 'effectRemove':act({type:'effectRemove',uid:id},uid());break;
case 'trigger':confirmAction('Déclencher l’effet','Le déclencheur doit être confirmé. Pour un Vengeur UA reçu par Wonq, sa réaction sera consommée.',{type:'trigger',uid:id});break;
case 'rest':rest(id);break;
case 'skill':test(skills[Number(id)][0],derived(get()).skills[Number(id)]);break;
case 'save':test('Sauvegarde '+abilities[Number(id)],derived(get()).saves[Number(id)]);break;
case 'check':test('Test de '+abilities[Number(id)],derived(get()).mods[Number(id)]+Math.floor(get().character.prof/2));break;
case 'initiative':test('Initiative',derived(get()).initiative);break;
case 'toolRoll':modal('Test d’instrument',select('ability','Caractéristique (choix MJ)',abilities.map((a,i)=>[i,a]),5)+rolls(),fd=>act({type:'roll',label:'Instrument maîtrisé',bonus:derived(get()).mods[Number(fd.get('ability'))]+get().character.prof,...rollParams(fd)}));break;
case 'item':itemEdit(id);break;
case 'newItem':itemEdit();break;
case 'deleteItem':{const item=clone(get().items.find(i=>i.id===id));confirmAction('Supprimer '+item.name,'Retirer cet objet et ses bonus éventuels. Annuler permet de le récupérer.',{type:'item',item,remove:true});break;}
case 'coins':modal('Monnaie',field('value','Pièces d’or',get().coins,'number'),fd=>act({type:'adjust',field:'coins',value:Number(fd.get('value'))}));break;
case 'adjust':jsonEditor('Compteurs — arbitrage MJ',get().resources,r=>{const n=clone(get());n.resources=r;act({type:'manualState',state:n});});break;
case 'editEffects':jsonEditor('Effets et silhouettes',{effects:get().effects,cortege:get().cortege},x=>{const n=clone(get());n.effects=x.effects;n.cortege=x.cortege;act({type:'manualState',state:n});});break;
case 'history':view='journal';journalTab='history';render();break;
case 'session':modal('Séance de spiritisme',`<p>Une heure, maximum trois participants volontaires au total, Wonq compris. Sort de niveau au plus égal au nombre de participants (1 à 3), Divination ou Nécromancie. Composantes requises.</p>${field('name','Sort retenu')}${field('participants','Participants (Wonq inclus)',3,'number')}${field('level','Niveau du sort',1,'number')}${select('school','École',[['Divination','Divination'],['Nécromancie','Nécromancie']],'Divination')}<label>Description / composantes<textarea name="description"></textarea></label>`,fd=>act({type:'session',name:fd.get('name'),participants:Number(fd.get('participants')),level:Number(fd.get('level')),school:fd.get('school'),description:fd.get('description')}));break;
case 'sessionCast':modal('Sort de séance',`<p>${esc(get().session.name)} — ${esc(get().session.description)}</p><p>Résolution et conditions à confirmer avec le MJ. Le coût sera suivi.</p>${select('level','Emplacement',Array.from({length:5-get().session.level},(_,i)=>[i+get().session.level,'N'+(i+get().session.level)]),get().session.level)}${select('cost','Temps de lancement',[['action','Action'],['bonus','Action bonus'],['reaction','Réaction']],'action')}${check('concentration','Concentration')}`,fd=>act({type:'sessionCast',level:Number(fd.get('level')),cost:fd.get('cost'),concentration:fd.has('concentration')}));break;
case 'registerNew':registerEdit();break;
case 'registerEdit':registerEdit(id);break;
case 'registerUse':modal('Où es-tu ?',`<p>10 minutes de méditation avec un lien personnel admissible. 1 utilisation par repos long.</p>${field('target','Absent recherché')}${select('answer','Réponse du MJ',[['Proche (<1,5 km)','Proche (<1,5 km)'],['Même plan','Même plan'],['Autre plan','Autre plan'],['Silence','Silence'],['Brouillé','Brouillé']],'Silence')}`,fd=>act({type:'registerUse',target:fd.get('target'),answer:fd.get('answer')}));break;
case 'newNote':noteEdit();break;
case 'note':noteEdit(id);break;
case 'deleteNote':{const n=clone(get().notes.find(n=>n.id===id));n.deleted=!n.deleted;n.updated=new Date().toISOString();commit({type:'note',note:n});$('#modal').close();render();notify(n.deleted?'Note placée dans la corbeille.':'Note restaurée.');break;}
case 'categories':categories();break;
case 'catUp':{const row=b.closest('[data-cat]');if(row.previousElementSibling)row.parentElement.insertBefore(row,row.previousElementSibling);break;}
case 'catRemove':b.closest('[data-cat]').remove();break;
case 'catAdd':{const k=uid();$('#category-list').insertAdjacentHTML('beforeend',`<div class="row" data-cat="${k}"><input name="cat-${k}" aria-label="Nom de catégorie" value="Nouvelle catégorie"><input type="color" name="color-${k}" aria-label="Couleur" value="#77bdb8" style="width:54px" class="fixed">${btn('↑','catUp','class="fixed"')}${btn('Retirer','catRemove','class="fixed"')}</div>`);break;}
case 'settings':settings();break;
case 'config':jsonEditor('Personnage — valeurs et descriptions',get(),n=>act({type:'manualState',state:n}));break;
case 'export':download('Wonq-partie.json',exportState());break;
case 'raw':download('Wonq-donnees-brutes.json',rawState());break;
case 'exportNotes':download('Wonq-journal.md',get().notes.filter(n=>!n.deleted).map(n=>`# ${n.title||'Sans titre'}\n\n${get().categories.find(c=>c.id===n.category)?.name||''} · ${n.session||''}\n\n${n.body}\n\nÉtiquettes : ${n.tags||''}\n`).join('\n---\n\n'),'text/markdown');break;
case 'import':modal('Importer une partie','<label>Fichier JSON<input id="import-file" type="file" accept=".json,application/json"></label><div id="import-preview"></div>',null);$('#import-file').onchange=async ev=>{try{const f=ev.target.files[0];if(!f)return;const next=parseImport(await f.text());modal('Vérifier avant remplacement',`<p>${esc(next.character.name)} : ${next.resources.hp} PV, ${next.resources.inspiration} inspirations.<br>${next.notes.length} notes, ${next.items.length} objets, rencontre ${next.encounter}.</p><p>La partie actuelle sera conservée comme sauvegarde précédente.</p>`,()=>{replace(next);$('#modal').close();render();notify('Partie importée.');});}catch(err){error(err)}};break;
case 'previous':modal('Récupérer la sauvegarde précédente','<p>La partie actuelle et la sauvegarde précédente seront échangées.</p>',()=>{restorePrevious();$('#modal').close();render();notify('Sauvegarde précédente restaurée.');});break;
case 'sources':{const r=await fetch('./sources.json'),pages=await r.json();modal('Sources & choix explicites',`<p>Le dossier prime pour le personnage et ses sorts. La table des Contes de l’application actuelle (variante UA) est conservée comme profil initial, avec choix du dossier dans les réglages.</p><p>Différences : Contes 1, 3, 5, 6, 7 et 8 ; Dissipation corrigée à CHA + Touche-à-tout ; sorts connus du dossier ; Lanterne du Retour facultative, quantité initiale 0. Aucun pouvoir de Karu n’est transféré.</p><a href="./ARBITRAGES.md" target="_blank">Lire les arbitrages détaillés</a>${pages.map((text,i)=>`<details><summary>Dossier · page ${i+1}</summary><div class="source-text">${esc(text)}</div></details>`).join('')}`,null);break;}
}}catch(err){error(err)}});
window.addEventListener('storage-error',e=>notify(e.detail,'damage'));
window.addEventListener('error',e=>console.error('Wonq',e.error));
render();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;offlineReady=true;const el=$('#offline-state');if(el)el.textContent='Disponible hors ligne';}).catch(()=>{const el=$('#offline-state');if(el)el.textContent='Hors ligne non préparé';});}
